apiVersion: v1
kind: Service
metadata:
  name: frontend-preview-service
  namespace: {{ .Values.namespace.name | default .Values.global.namespace }}
  labels:
    {{- include "bluegreen-deploy.frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.servicePreview.type }}
  ports:
  - port: {{ .Values.frontend.servicePreview.port }}
    targetPort: {{ .Values.frontend.servicePreview.targetPort }}
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
